### ISSUE TITLE
MissingPluginException(No implementation found for method end_room on channel hmssdk_flutter)

### ISSUE THREAD

**Issue by khurramrizvi** [100mslive/100ms-flutter#1166]
Whenever I try to initialise and access hmssdk from a dart isolate, MissingPluginException is thrown.

I tried registering the plugin using the ```DartPluginRegistrant.ensureInitialized();```, however it doesn't seems to work.

This seems something similar to https://github.com/fluttercommunity/flutter_workmanager/issues/360

Please guide me on this.

Thanks!

**Comment by ygit** [comment]
hey @khurramrizvi 
can you share the entire error logs?
Also, have you tried initialisation without Dart isolate?

**Comment by ygit** [comment]
hey @khurramrizvi 
Were you able to resolve this?

**Comment by khurramrizvi** [comment]
@ygit It's not resolved, I will attach the error log shortly.

**Comment by ygit** [comment]
hey @khurramrizvi 
Closing this issue now.
Feel free to reopen this or connect over Discord: https://100ms.live/discord
