### ISSUE TITLE
The 'Pods-Runner' target has frameworks with conflicting names: webrtc.xcframework

### ISSUE THREAD

**Issue by mohd-afid** [100mslive/100ms-flutter#1171]
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:666:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:164:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    
I am using the flutter_webrtc and hmssdk_flutter packages.
There is no problem in Android, but the above error appears in iOS.

**Comment by ygit** [comment]
hey @mohd-afid 
Any specific reason why you are using both `flutter_webrtc` and `hmssdk_flutter`?
Removing `flutter_webrtc` and only using `hmssdk_flutter` will resolve this error

**Comment by mohd-afid** [comment]
@ygit I already developed a complete video conference app using the flutter_webrtc package. So I am trying to do picture-in-picture in IOS using the hmssdk_flutter package. Is there any idea to do pip mode in iOS?

**Comment by mohd-afid** [comment]
I know, I already followed this document, but I can't install the hmssdk_flutter package in our project.

**Comment by ygit** [comment]
@mohd-afid You cannot have both `flutter_webrtc` & `hmssdk_flutter` in the project.

**Comment by mohd-afid** [comment]
@ygit I've already done all of my features with flutter_webrtc, so is there any other solution for pip mode in iOS?

**Comment by ygit** [comment]
No @mohd-afid

**Comment by ygit** [comment]
hey @mohd-afid 
Have you considered/started integrating 100ms Flutter package?
Anything else we can assist with?

**Comment by ygit** [comment]
hey @mohd-afid 
Closing this ticket now, let me know if you need anything else.
You can also chat with us on Discord: https://100ms.live/discord
