### ISSUE TITLE
hand raise icon is not visible

### ISSUE THREAD

**Issue by qapraveen100ms** [100mslive/100ms-flutter#1222]
### Description

user join as hls viewer/host
hand raise icon is not clearly visible to user

### 100ms Flutter Version

Model - Redmi Note 8 Pro Android Version - 10 QP1A.190711.020 App version - 1.4.83 (218) HMS SDK - 1.4.0 Android SDK - 2.6.0

### Steps to reproduce

join as host/hls and check hand raise icon on Jay mobile

### Expected results

should be visible

### Code example, screenshot, or link to a repository

NA

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

NA

**Comment by Decoder07** [comment]
Closing the issue as not able to repro.
