### ISSUE TITLE
getting 500 rpc error on reconnecting

### ISSUE THREAD

**Issue by qapraveen100ms** [100mslive/100ms-flutter#1266]
### Description

QA room
getting 500 rpc error on reconnecting

### 100ms Flutter Version

1.5.0

### Steps to reproduce

join room
disconnect
reconnect

### Expected results

should rejoin room and resume call

### Code example, screenshot, or link to a repository

NA

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

NA

**Comment by ygit** [comment]
It was an issue due to Real-Time database used for the new Session Store on QA Rooms

**Comment by ygit** [comment]
The issue has been deployed by Server side
