### ISSUE TITLE
🚀 Add local recording 

### ISSUE THREAD

**Issue by user97116** [100mslive/100ms-flutter#1389]
- Should record camera view with recording with or without networks 
- Should save to specific path

**Comment by ygit** [comment]
hey @user97116 
Can you share more details about this?

**Comment by user97116** [comment]
Is it possible to use recording of local preview in meating like https://pub.dev/packages/camera

**Comment by user97116** [comment]
@ygit I want to record video of local preview of camera when I join room

**Comment by ygit** [comment]
hey @user97116 
No, we do not provide support for recording video before Joining the Room.
Once you join a Room, you can record the local Peer's video camera feed.

Do refer this doc for more details: https://www.100ms.live/docs/server-side/v2/how-to-guides/recordings/overview

**Comment by user97116** [comment]
@ygit it is possible to access local preview stream as byte stream
