### ISSUE TITLE
do not reveive onTrackUpdate❓ 

### ISSUE THREAD

**Issue by redfieldchristabel** [100mslive/100ms-flutter#1417]
hi there,  I'm using flutter 100ms SDK, but I notice the HMSUpdateListener method  " onTrackUpdate" are not updated or triggered,

but I can see the log of WebSocket in the Flutter run log, the same method got triggered.

but other methods are triggered like onJoin, on peerUpdate.

do I need to do something before?

here is the log I mentioned above.

I also attach some pictures the of initialization and the provider consuming the notifier.

I also attach some pictures of how I tried to get the remote video track to be consumed by the  HMSVideoView widget but the remote peer held no videoTrack instance at all.

do I need to use  HLS URL to watch the live stream or can I use the HMSVideoView widget?

![image](https://github.com/100mslive/100ms-flutter/assets/69151253/995784d0-2004-437d-873c-508373120c3c)

![image](https://github.com/100mslive/100ms-flutter/assets/69151253/3c7ae1ae-9012-4c45-879c-a37756205a36)

![image](https://github.com/100mslive/100ms-flutter/assets/69151253/a15d69bc-5fa5-4a4d-afb7-7c6247f6e719)

![image](https://github.com/100mslive/100ms-flutter/assets/69151253/0eb3d617-7382-47dc-a832-5248967f61b3)

**Comment by Decoder07** [comment]
Hi @redfieldchristabel 
To view HLS stream you will need the hls m3u8 url. Checkout the docs here: [hls-docs](https://www.100ms.live/docs/flutter/v2/how-to-guides/record-and-live-stream/hls)

Does the remote peer have permission to publish video ?
Attaching the discord thread link here: https://discord.com/channels/843749923060711464/1128547015597490358
