### ISSUE TITLE
📚 Add Prebuilt Quickstart app as Example app of Room Kit package

### ISSUE THREAD

**Issue by ygit** [100mslive/100ms-flutter#1593]
# 📚 Documentation Task

- The Prebuilt Quickstart app on public docs should be used as Example app for RoomKit package

**Comment by vinayaknolastname** [comment]
Hey @ygit  i want to contribute in this task can u please elaborate a little bit, so you want a example app using hms_ui_kit.. like zoom clone some thing like that..

**Comment by ygit** [comment]
hey @vinayaknolastname 

With this task, we want to create an app which uses the `hms_room_kit` package. 
You can refer to the Guide here to create the app: https://www.100ms.live/docs/flutter/v2/quickstart/prebuilt
Once done, this app will be used as the Example app for the `hms_room_kit` package.
When you raise the Pull Request, add screenshots of the app UI in the PR.

Thanks for taking this up. Really appreciate it.

**Comment by ygit** [comment]
hey @vinayaknolastname 
This is awesome!
Thanks for contributing 🙌
