### ISSUE TITLE
Explore how we can implement Flutter for Web

### ISSUE THREAD

**Issue by ygit** [100mslive/100ms-flutter#163]

**Comment by johnwcchau** [comment]
for your consideration i have created a web plugin for myself https://github.com/johnwcchau/hmssdk_flutter_web, not complete and with bugs, but you may want to use that as starting point?

**Comment by ygit** [comment]
@johnwcchau This is awesome. Will definitely check it out 🙌

**Comment by wisedev-pstach** [comment]
@ygit, @johnwcchau  Is there any way possible now to run it with Web? I tried package mentioned by @johnwcchau  but unfortunatelly I get errors on try to join room. Maybe i setup it wrong, is there maybe some documentation or example with this configured?

**Comment by johnwcchau** [comment]
are you using hmssdk_flutter 0.7.3? the package currently only support
0.7.3 so please change your pubspec.yaml.
hmssdk_flutter: 0.7.3
I will update the code for latest hmssdk but not in priority until my
customer give me go sign to continue the project.

**Comment by Nasseh123** [comment]
Hello can we use it on web now?
