### ISSUE TITLE
Add support for Windows and MacOS 🚀 

### ISSUE THREAD

**Issue by kausikMR** [100mslive/100ms-flutter#1658]
I would love to use 100ms on my windows and macOS but due to the lack of support, Im finding a way to achieve it.

**Comment by ygit** [comment]
@kausikMR Glad to see your interest. 
Can you share more details about how you plan to use the 100ms SDK on Windows & MacOS? 
Does a web version of the 100ms SDK work? 
Any OS-specific features you are looking forward to?

**Comment by kausikMR** [comment]
We are trying to use 100ms for conducting online workshops, we have web, android and iOS currently, we also have audience on desktop (windows and mac) currently we are using livekit for the windows and mac. we have already migrated our android and iOS implementations from livekit to 100ms. now we need desktop support from you.

**Comment by ygit** [comment]
@kausikMR That's good to hear. 
We currently don't support Desktop but have it on our long-term roadmap. 
Can we connect over a call once to discuss this further? 
Do book a convenient time here: https://calendly.com/yogesh-singh-100ms/30min

**Comment by ygit** [comment]
hey @kausikMR 
Checking in; were you able to see my last message?

**Comment by damonique-dev** [comment]
@ygit is supporting Flutter Web on the roadmap as well? My company is considering switching from livekit to 100ms as well and we will have a web presence soon using Flutter.
