### ISSUE TITLE
🐛  while doing xcode build getting this HMSAudioAction.swift:9:8 No such module 'HMSSDK'  in Xcode 15.2 i have already pod installed and checked all things while removing hmssdk completely from project my project runs smoothly in xcode 

### ISSUE THREAD

**Issue by himanshu-binarychai** [100mslive/100ms-flutter#1703]
### Description

I am Using latest version of hmssdk 1.9.8 but still getting this error, after pos install update 

### 100ms Flutter Version

3.7.12 flutter sdk

### Steps to reproduce

it is working fine and debug in android but i am opening this project in xcode  then while build i am getting this error 

### Expected results

i wanted that why it is not getting the module but in pod.lock its version and package mentioned 

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```dart
```

### Logs

<details>
<summary>Logs</summary>

```console

Automatically signing iOS for device deployment using specified development team in Xcode project: WHZAQ4UY8D
Running pod install...                                           2,494ms
Running Xcode build...                                                  
Xcode build done.                                           21.3s
Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'HMSSDK'
/Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSAudioAction.swift:8:7


Encountered error while building for device.

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.6.3 22G436 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2023.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.86.0)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone . Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] HTTP Host Availability

```

</details>

**Comment by ygit** [comment]
hey @himanshu-binarychai 
Ensure that you have run `flutter pub get` at the appropriate directory level.
We are not able to reproduce this issue.
If possible, can you share a zip of the project where this issue is reproducible?

**Comment by himanshu-binarychai** [comment]
i have already run pub get @ygit 


SwiftEmitModule normal x86_64 Emitting\ module\ for\ hmssdk_flutter (in target 'hmssdk_flutter' from project 'Pods')
    cd /Users/binarychai3/Documents/Flutter/Flutter\ Projects/massh/ios/Pods
    builtin-swiftTaskExecution -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSAudioAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSAudioDeviceAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSAudioFilePlayerNodeExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSCameraControlsAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSChangeTrackStateRequestExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSCommonAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSErrorExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSErrorLogger.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Views/HMSFlutterPlatformView.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Views/HMSFlutterPlatformViewFactory.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSHLSAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSCueExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSPlaybackStateExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSPlayerAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSPlayerStatsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Views/HMSHLSPlayerView.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Views/HMSHLSPlayerViewFactory.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSStatsHandler.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/HLSPlayer/HMSHLSStreamViewController.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSHLSVariantExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSMessageAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSMessageExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSMessageRecipientExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSMicNodeExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSNetworkQualityExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSPeerAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSPeerExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSPeerListIteratorAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSPeerListIteratorExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSPermissionExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSPIPAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Views/HMSPiPView.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSPublishSettingsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSRecordingAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSRemoteVideoTrackAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSRemovedFromRoomExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSResultExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSRoleExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSRoomAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSRoomExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSSessionStoreAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSessionStoreKeyChangeListener.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSimulcastExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSimulcastLayerDefinitionExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSimulcastLayerSettingsPolicyExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSimulcastSettingsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSpeakerExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSStatsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSStreamingStateExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSubscribeDegradationPolicyExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSSubscribeSettingsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSTrackExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSTrackSettingsExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Actions/HMSVideoAction.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/Models/HMSVideoResolutionExtension.swift /Users/binarychai3/.pub-cache/hosted/pub.dev/hmssdk_flutter-1.9.8/ios/Classes/SwiftHmssdkFlutterPlugin.swift -target x86_64-apple-ios12.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk -I /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Products/Debug-iphonesimulator/hmssdk_flutter -F /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Products/Debug-iphonesimulator/hmssdk_flutter -F /Users/binarychai3/Documents/Flutter/Flutter\ versions/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator -no-color-diagnostics -enable-testing -g -import-underlying-module -module-cache-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -D COCOAPODS -serialize-debugging-options -const-gather-protocols-file /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter_const_extract_protocols.json -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/binarychai3/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/binarychai3/Documents/Flutter/Flutter\ Projects/massh/ios/Pods -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -ivfsstatcache -Xcc /Users/binarychai3/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.2-21C52-4f2951bfe8f3cd53c99228b0131e163e.sdkstatcache -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/hmssdk_flutter-generated-files.hmap -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/hmssdk_flutter-own-target-headers.hmap -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/hmssdk_flutter-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/hmssdk_flutter-project-headers.hmap -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Products/Debug-iphonesimulator/hmssdk_flutter/include -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/DerivedSources-normal/x86_64 -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/DerivedSources/x86_64 -Xcc -I/Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG\=1 -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -Xcc -ivfsoverlay -Xcc /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/unextended-module-overlay.yaml -module-name hmssdk_flutter -disable-clang-spi -target-sdk-version 17.2 -target-sdk-name iphonesimulator17.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -emit-module-doc-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter.swiftdoc -emit-module-source-info-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter.swiftsourceinfo -emit-objc-header-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter-Swift.h -serialize-diagnostics-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter-master-emit-module.dia -emit-dependencies-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter-master-emit-module.d -o /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter.swiftmodule -emit-abi-descriptor-path /Users/binarychai3/Library/Developer/Xcode/DerivedData/Runner-adhjjwrhvqugvehexeesrqysivyp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hmssdk_flutter.build/Objects-normal/x86_64/hmssdk_flutter.abi.json
    
    
    
    
     this is the complete log still unable to fix this issue can you please take a look into this

**Comment by ygit** [comment]
@himanshu-binarychai are you trying to run on iPhone device or Simulator?

**Comment by himanshu-binarychai** [comment]
> @himanshu-binarychai are you trying to run on iPhone device or Simulator?

i have tried it on both

**Comment by himanshu-binarychai** [comment]
basically this project is running well in my previous mac with intel chip but i when i am trying to run it on mac m1 then i am getting this error while buildiing in xcode @ygit

**Comment by ygit** [comment]
hey @himanshu-binarychai were you able to resolve this issue?

**Comment by ygit** [comment]
Good to hear!
