### ISSUE TITLE
How can I use flutter_webrtc  and hmssdk_flutter package together❓ 

### ISSUE THREAD

**Issue by vaishnavijlk** [100mslive/100ms-flutter#1775]
I have a requirement which I need to use these two packages together. I get this error when I try to run my application. 

build.gradle: 
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
    implementation 'com.android.support:multidex:2.0.1'
    compileOnly 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.3.3'
    implementation 'io.github.webrtc-sdk:android:114.5735.10'
}

pubspec.yaml:
  flutter_webrtc: ^0.10.6
  hmssdk_flutter: ^1.10.2

<img width="1042" alt="Screenshot 2024-05-30 at 2 44 01 PM" src="https://github.com/100mslive/100ms-flutter/assets/152834271/8845d5fa-4902-42ad-8c4f-865ee79f10ca">

**Comment by Decoder07** [comment]
Hi @vaishnavijlk this is not possible since `hmssdk_flutter` internally uses native webrtc libraries. Can you please explain why do you need both the dependencies ?

**Comment by ygit** [comment]
@vaishnavijlk Using both `hmssdk` & WebRTC is not possible. Have you tried to send the stethoscope audio and usb camera inputs via a 100ms Room?
We can get over a call to discuss more about this. 
Book a slot here: https://calendly.com/yogesh-singh-100ms/30min
