### ISSUE TITLE
📚 VIDEO CAMERA AND ROOM UPDATE ISSUE - IOS

### ISSUE THREAD

**Issue by james-rosales** [100mslive/100ms-flutter#1778]
IOS all device
The camera sometimes work, sometimes not. and when using the toggle it is not in sync.
The room update is late, when another user join the room update does not call. but when the user leaves the update call

But this features works fine in android

**Comment by Decoder07** [comment]
Hi @james-rosales which sdk version are you using ?
Also are you getting `onPeerListUpdate` when a new peer joins ?

**Comment by james-rosales** [comment]
for package this is the version hmssdk_flutter 1.10.2
the flutter version i use is 3.22.0

i dont get any prints onpeerlistupdate. i will send tomorrow video for ios

**Comment by james-rosales** [comment]
Here is attachment on iOS device, the camera sometimes works sometimes black. But in android it perfectly works fine.
Then the in session it was working when my flutter version is 3.16.5 but when i upgrade to 3.22.0 its not working


https://github.com/100mslive/100ms-flutter/assets/114055648/87da918d-31f8-4705-96fb-650f35424dc3

`class _JoinRoomBodyState extends State<JoinRoomBody>
    implements HMSPreviewListener {
  late JoinRoomBloc _bloc;
  late HMSSDK hmsSDK;
  late HMSConfig hmsConfig;
  HMSVideoTrack? videoTrack;
  bool isVideoOn = false;
  bool isAudioOn = false;
  bool loading = true;
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      initHMSSDK();
    });
  }

  @override
  void dispose() {
    super.dispose();
    hmsSDK.removePreviewListener(listener: this);
    hmsSDK.cancelPreview();
  }

  Future<void> initHMSSDK() async {
    hmsSDK = HMSSDK();
    await hmsSDK.build(); // ensure to await while invoking the `build` method

    dynamic authToken = await hmsSDK.getAuthTokenByRoomCode(
        roomCode: _bloc.state.roomCode?.code ?? '');
    hmsConfig = HMSConfig(
      userName: _bloc.state.student?.fullname ?? '',
      authToken: authToken,
    );

    //Here this is an instance of a class that implements HMSPreviewListener, that is, Preview
    hmsSDK.addPreviewListener(listener: this);
    hmsSDK.preview(config: hmsConfig);
  }

  @override
  void onAudioDeviceChanged(
      {HMSAudioDevice? currentAudioDevice,
      List<HMSAudioDevice>? availableAudioDevice}) {}

  @override
  void onHMSError({required HMSException error}) {}

  @override
  void onPeerUpdate({required HMSPeer peer, required HMSPeerUpdate update}) {}

  @override
  void onPreview({required HMSRoom room, required List<HMSTrack> localTracks}) {
    for (var track in localTracks) {
      if (track.kind == HMSTrackKind.kHMSTrackKindVideo) {
        setState(() {
          videoTrack = track as HMSVideoTrack;
          loading = false;
        });
      }
      if (track.kind == HMSTrackKind.kHMSTrackKindAudio) {
        setState(() {
          isAudioOn = !(track.isMute);
        });
      }
    }
    _bloc.add(RoomOnChanged(room));
  }

  @override
  void onRoomUpdate({required HMSRoom room, required HMSRoomUpdate update}) {
    _bloc.add(RoomOnChanged(room));
  }

  @override
  void onPeerListUpdate(
      {required List<HMSPeer> addedPeers,
      required List<HMSPeer> removedPeers}) {}`

**Comment by Decoder07** [comment]
Hey @james-rosales Can you book a call here: https://calendly.com/saxena-pushpam/30min
Lets debug it on call.

**Comment by james-rosales** [comment]
Sure but on monday, because the ios device is at my workplace.

**Comment by Decoder07** [comment]
Hey @james-rosales are you joining ?

**Comment by Decoder07** [comment]
@james-rosales you can follow this flow: https://www.100ms.live/docs/flutter/v2/how-to-guides/set-up-video-conferencing/preview
Let me know if you have any questions.

**Comment by james-rosales** [comment]
okay sir thank you

**Comment by Decoder07** [comment]
Hey @james-rosales were you able to resolve the issue ?

**Comment by james-rosales** [comment]
I've managed to fix the issue regarding the Room List Update Listener, but
the video camera still not fix. Based on my test, the video camera is
working fine at the first try, but when I Leave the preview screen to go
back the dashboard and go back again to preview screen it only shows black
screen.

In the dispose i called the hmssdk cancel preview and destroy.

James Carlo Rosales
Software Engineer
KODA Kollectiv
Cebu, PH
***@***.*** ***@***.***>
+63 931 060 6090

CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally protected
from disclosure. If you are not the intended recipient of this message or
their agent, or if this message has been addressed to you in error, please
immediately alert the sender by reply email and then delete this message
and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is strictly prohibited.

**Comment by Decoder07** [comment]
@james-rosales Can you share a minimal app where you are able to repro this issue. I will have a look at the code.

**Comment by james-rosales** [comment]
I can give you the full code

**Comment by Decoder07** [comment]
Okay, please share the zipped project or git repo. I will check it.

**Comment by ygit** [comment]
@james-rosales Were you able to resolve this issue?

**Comment by Gurvan2** [comment]
Hello, I have the same issue. When I leave a call and return to it with an iOS phone, the camera is reversed. The issue is reproducible with the sample apps (block in my case: https://github.com/100mslive/100ms-flutter/tree/main/sample%20apps/bloc) if you add possibility to return to the main screen.

Even if isVideoMute and isOffScreen are both false, the video stream is sent and received by the other participant.

And when you click to activate the camera and set isVideoMute, the camera returns to a black screen.
