### ISSUE TITLE
🐛 intl version mismatch

### ISSUE THREAD

**Issue by sambitraze** [100mslive/100ms-flutter#1781]
### Description

i am using intl, flutter localization and hms_room_kiit in my flutter project but I getting the following issue

Because flutter_localization 0.2.0 depends on flutter_localizations from sdk which depends on intl 0.19.0, flutter_localization 0.2.0 requires intl 0.19.0.
And because hms_room_kit >=1.0.9 depends on intl ^0.18.0, flutter_localization 0.2.0 is incompatible with hms_room_kit >=1.0.9.
So, because winhealth depends on both flutter_localization 0.2.0 and hms_room_kit ^1.1.2, version solving failed.

### 100ms Flutter Version

hms_room_kit: ^1.1.2

### Steps to reproduce

use 

flutter_localization: 0.2.0
hms_room_kit: ^1.1.2
intl: 

### Expected results

good build

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```dart
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by Decoder07** [comment]
Hi @sambitraze can you try lowering `flutter_localization` to a version which depends on `intl`: `0.18.0` .

**Comment by sambitraze** [comment]
I cant bump down the version as many other packages which we are using in the app are relying on 1.19.0 intl

**Comment by Decoder07** [comment]
@sambitraze we will have to increase the minimum version for `hmssdk_flutter` to `3.0.0` for this change. Let me discuss this internally once.

**Comment by AmirAhmedDarrag** [comment]
This issue still exists there and no actions have been taken until yet!!!!

**Comment by Decoder07** [comment]
Hi @AmirAhmedDarrag this will get resolved in the upcoming release.

**Comment by AmirAhmedDarrag** [comment]
Hi when is the upcoming release @Decoder07 i have a demo after one week

**Comment by Decoder07** [comment]
@AmirAhmedDarrag @sambitraze Can you try with [hms_room_kit](https://pub.dev/packages/hms_room_kit) version `1.1.5`, we have updated the `intl` version.

**Comment by sambitraze** [comment]
again the issue has reappeared.
