### ISSUE TITLE
🐛 1,290 devices no longer supported due to autofocus

### ISSUE THREAD

**Issue by tgpsantos** [100mslive/100ms-flutter#1816]
### Description

Hi guys,

After adding hms sdk and submitting our new version to the Play Store, we're getting a warning that hundreds of devices will stop being supported. A subset of them seem recent / up-to-date.

The reason is they don't support the mandatory autofocus feature in HMS SDK.

Is it really mandatory, or can we override so it's not necessarily required ?

### 100ms Flutter Version

any

### Steps to reproduce

1. have an existing app in Play Store
2. add hmssdk to dependencies and generate bundle
3. upload new bundle to Play Store

### Expected results

No drop in supported devices

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```dart
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by ygit** [comment]
@tgpsantos are you using the `hms_room_kit` package or only `hmssdk_flutter` ?

**Comment by tgpsantos** [comment]
> @tgpsantos are you using the `hms_room_kit` package or only `hmssdk_flutter` ?

hmssdk_flutter only
