### ISSUE TITLE
IOS app crashes when joining audio room

### ISSUE THREAD

**Issue by Nijinsha** [100mslive/100ms-flutter#182]
Unsupported value: <HMSSDK.HMSLocalPeer: 0x280dff200> of type HMSSDK.HMSLocalPeer
*** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:334
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x18349405c 0x19b9aef54 0x184d5599c 0x1150d0138 0x1150d07c0 0x1150cd890 0x107bd9bec 0x107bcdea4 0x1150cd7f8 0x114c19f00 0x114f255f0 0x114eca39c 0x114ecd994 0x1834a9278 0x18342dc50 0x18342844c 0x183406c68 0x18341a3c8 0x19ec2b38c 0x185dc0060 0x185b3db8c 0x1047a46cc 0x104d99a24)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT

**Comment by ygit** [comment]
@Nijinsha were you able to resolve this issue?
