### ISSUE TITLE
cannot access HMSUpdateListener       flutterEngine.getPlugins().add(new live.hms.hmssdk_flutter.HmssdkFlutterPlugin());

### ISSUE THREAD

**Issue by chiraghashtech** [100mslive/100ms-flutter#201]

**Comment by Arunshaik2001** [comment]
add the dependency of 100ms sdk in android->build.gradle file

**Comment by chiraghashtech** [comment]
![Screenshot 2021-11-01 at 12 02 01 PM](https://user-images.githubusercontent.com/90820625/139631057-7b6ea78d-2be0-45d0-8877-18a9bcbf61ca.png)
  
This is my Android build.gradle file please watch and reply

**Comment by Arunshaik2001** [comment]
at the bottom, u will find dependencies add this inside that ->implementation 'com.github.100mslive:android-sdk:v2.1.6'

**Comment by ygit** [comment]
@chiraghashtech were you able to resolve the issue?

**Comment by chiraghashtech** [comment]
thank you..
