### ISSUE TITLE
onUpdateSpeakers not updating every one second (as mentioned in the docs), it updates only when someone speaks.

### ISSUE THREAD

**Issue by abbas2501** [100mslive/100ms-flutter#208]
Shouldn't it return an empty list of members if no one is speaking after every 1 second ?

**Comment by Arunshaik2001** [comment]
you will not get updates every second

**Comment by abbas2501** [comment]
```
 /// This is called every 1 second with a list of active speakers
  ///
  ///    A HMSSpeaker object contains -
  ///    - peerId: the peer identifier of HMSPeer who is speaking
  ///    - trackId: the track identifier of HMSTrack which is emitting audio
  ///    - audioLevel: a number within range 1-100 indicating the audio volume
  ///
  /// A peer who is not present in the list indicates that the peer is not speaking
  ///
  /// This can be used to highlight currently speaking peers in the room
  /// - Parameter speakers: the list of speakers
  void onUpdateSpeakers({required List<HMSSpeaker> updateSpeakers});

```

@Arunshaik2001 thanks for the reply. \

The above code is pasted from pub.dev page of hms_sdk. The first line indicates otherwise -- also if we don't get updates every second, how to know if nobody's speaking?

So for eg -- 

A is speaking (we show A speaking with a blue border around A's image in UI)
After 4 seconds, A stopped speaking
Now, nobody is speaking. How would you know that A stopped speaking?
Apparently, you can't until someone else starts speaking with A, not on that new list of speakers.

Help me if I'm missing out on something here?

**Comment by abbas2501** [comment]
@ygit can you help me out ?

**Comment by abbas2501** [comment]
@ygit closed because resolved or will not be resolved ?
