### ISSUE TITLE
How To Find The Peer id Of All listeners When admin  to change role 

### ISSUE THREAD

**Issue by chiraghashtech** [100mslive/100ms-flutter#212]

**Comment by ygit** [comment]
@chiraghashtech can you describe what are you looking for?

**Comment by chiraghashtech** [comment]
How to use user id as peer id while changing role?

**Comment by ygit** [comment]
Every `HMSPeer` object has [`customerUserId`](https://docs.100ms.live/api-reference/flutter/v2/hmssdk_flutter/HMSPeer-class.html) which you can set while [joining a room](https://docs.100ms.live/flutter/v2/features/join).

When you want to do Change Role, you need to pass `peer_id` to the `changeRole` API. You can filter through the list of peers in the room via `customerUserId` & get the appropriate `HMSPeer` object.

https://docs.100ms.live/flutter/v2/features/change-role

**Comment by ygit** [comment]
@chiraghashtech were you able to resolve this issue?

**Comment by chiraghashtech** [comment]
how to find all listeners peer id?

**Comment by Arunshaik2001** [comment]
in hmsroom instance which you will find in onJoin call there is a list of peers. so u can get peer ids from there

**Comment by ygit** [comment]
@chiraghashtech were you able to resolve this issue?

**Comment by chiraghashtech** [comment]
yes
