### ISSUE TITLE
Ensure clients can create multiple instances of HMSMeeting

### ISSUE THREAD

**Issue by ygit** [100mslive/100ms-flutter#224]
Clients should be able to create an instance of 100ms SDK > Join Room > Leave & they destroy the instance.
Then create a new instance of 100ms SDK > Join > Leave > Destroy

Ensure we don't have a singleton or store HMSMeeting instances within the SDK

**Comment by ygit** [comment]
@Arunshaik2001 Can we test this scenario?

**Comment by Arunshaik2001** [comment]
> @Arunshaik2001 Can we test this scenario?

ok, I will check
