### ISSUE TITLE
Add button to share all logs from the sample app 

### ISSUE THREAD

**Issue by ygit** [100mslive/100ms-flutter#231]
1. All the console logs from the sample app should be logged in a text file on the device
2. On clicking of the button - "Report Issue" a prompt should appear to share this file along with some message

**Comment by Decoder07** [comment]
Currently this functionality is commented in the build.

**Comment by ronit100ms** [comment]
Not able to send logs from the "Send Logs" button on the app
Steps:
click settings button
click send logs cta
share on the desired app
"Cannot send. Try again" (File size: 0B txt)
