### ISSUE TITLE
Room link is invalid

### ISSUE THREAD

**Issue by andim27** [100mslive/100ms-flutter#268]
I/flutter (11913): {token: null, msg: Room link is invalid, status: 404, api_version: 2.0.148}

**Comment by ygit** [comment]
@andim27 which link are you trying?
Try this link: https://yogi.app.100ms.live/meeting/nih-bkn-vek

**Comment by ygit** [comment]
@andim27 were you able to resolve the issue?

**Comment by andim27** [comment]
Now it works/The broken link was: Check your codebase please))

**Comment by ygit** [comment]
yea, that room has been permanently disabled now. On [develop](https://github.com/100mslive/100ms-flutter/tree/develop) branch it's updated.
