### ISSUE TITLE
The app gets crashed and come out when hmsSDK build

### ISSUE THREAD

**Issue by swethamano** [100mslive/100ms-flutter#504]
issue logged in console:
W/VideoCapabilities(30725): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(30725): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(30725): Unsupported mime video/divx
W/VideoCapabilities(30725): Unsupported mime video/divx4

**Comment by Arunshaik2001** [comment]
> issue logged in console: W/VideoCapabilities(30725): Unrecognized profile/level 0/3 for video/mpeg2 W/VideoCapabilities(30725): Unrecognized profile/level 0/3 for video/mpeg2 W/VideoCapabilities(30725): Unsupported mime video/divx W/VideoCapabilities(30725): Unsupported mime video/divx4

On which line of hmssdk code is this happening?

**Comment by swethamano** [comment]
While startpreview in hmsdk line,
This works fine in debug but in release, the app is crashed. Am using the demo token generated in 100ms dashboard

**Comment by Arunshaik2001** [comment]
Hi @swethamano have u gone through progaurd rules?

**Comment by swethamano** [comment]
Hai @Arunshaik2001  yeah, I have added all the permissions as per the document given

**Comment by ygit** [comment]
@swethamano Ensure that you have the correct proguard rules setup: https://www.100ms.live/docs/flutter/v2/features/integration#proguard-configuration

**Comment by swethamano** [comment]
Thanks, it worked!!! @ygit  @Arunshaik2001
