### ISSUE TITLE
Is it possible to do live streaming? [Question]

### ISSUE THREAD

**Issue by Nader2004** [100mslive/100ms-flutter#505]
Hello. I am totally new to 100ms. I know it supports video conferencing, but does it support live streaming. Something like instagram live or Youtube live where you can go live to thousands of Audiences. And if it possible could you please point me to the right documentation or the method to create it. Thanks!

**Comment by aakashbajaj** [comment]
Hi @Nader2004 
You can use RTMP streaming for the mentioned use case.
100ms docs - https://www.100ms.live/docs/server-side/v2/features/rtmp-streaming-and-browser-recording

**Comment by ygit** [comment]
@Nader2004 Yes, live streaming is supported.
Here are the Flutter docs for RTMP: https://www.100ms.live/docs/flutter/v2/features/recording
Also, check out HLS Streaming: https://www.100ms.live/docs/flutter/v2/features/hls

**Comment by Nader2004** [comment]
Hey @ygit  and @aakashbajaj thanks for responding, I will check these sources out.
