### ISSUE TITLE
Add support for Flutter Web

### ISSUE THREAD

**Issue by madhurgupta10** [100mslive/100ms-flutter#51]
Hi, we are using Flutter web for our WebApp and we need to integrate RTC. 100ms seems very powerful and we would like to give it a try.

At the moment we are not sure if it is supported for "Flutter for Web" or other native desktop platforms like Windows, Linux and macOS.

Let us know if it is supported already or if not, you guys have any plans to support it anytime soon!

**Comment by Akashgoswami1** [comment]
@madhurgupta10 Thanks for your comment. We do have a native electron version for desktop windows and mac. We are working on the flutter app and we should be done with it in the next few weeks.

**Comment by Akashgoswami1** [comment]
@madhurgupta10 Do let us know if you have other queries as well. We would happy to help

**Comment by madhurgupta10** [comment]
@Akashgoswami1 okay thanks.
