### ISSUE TITLE
Bad Request on joining

### ISSUE THREAD

**Issue by KevalPrajapati** [100mslive/100ms-flutter#528]
I get this on joining
`internalConnect:: failed :x: [error=HTTPError: Bad Request [code=401, action=INIT, description=Received , cause=null]]`

 `A connection to https://prod-init.100ms.live/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE); `

So here is what I do

```
_hmsConfig = HMSConfig(
      authToken: token,
      userName: profile.user.name,
    );
    await hmsSDK.build();
```

    hmsSDK.addUpdateListener(listener: HMSListener(this, profile, room));
    hmsSDK.join(config: _hmsConfig!);

**Comment by ygit** [comment]
@KevalPrajapati Ensure that you are using the correct Auth Token to join the room. It should contain the `roomId` & `role` - `role` is case-sensitive

**Comment by KevalPrajapati** [comment]
> @KevalPrajapati Ensure that you are using the correct Auth Token to join the room. It should contain the `roomId` & `role` - `role` is case-sensitive

@ygit I am sure about that. That shouldn't be the issue.

**Comment by ygit** [comment]
Closing as it's resolved now
