### ISSUE TITLE
Hi! Does this work on Flutter Web?

### ISSUE THREAD

**Issue by robmr88** [100mslive/100ms-flutter#550]
Hi! Does this work on Flutter Web?

**Comment by ygit** [comment]
hey @robmr88 
Flutter Web is not supported yet. I would recommend to use our Web SDK: https://www.100ms.live/docs/javascript/v2/foundation/basics

**Comment by robmr88** [comment]
Thanks for the fast reply!
Are there plans to make it available for Flutter Web in the near future?

**Comment by ygit** [comment]
Yes, it is on our roadmap. But do not have any timelines finalized yet. 
You can join our Discord to stay in loop for updates: https://100ms.live/discord

**Comment by Zeeshan0201** [comment]
@ygit  any update on this?

**Comment by Zeeshan0201** [comment]
okay thanks for quick response.
