### ISSUE TITLE
App crashing after join is called.

### ISSUE THREAD

**Issue by asmitzz** [100mslive/100ms-flutter#750]
Version tried
Flutter 3.0.5
hmssdk_flutter: ^0.7.3

**What happens -**

Using Server-Side API
1. Create management token.
2. Create room using management token. ( can see room on the dashboard )
3. Generate app token using room that we have created in the step 2.
4. Use that app token to join the room.
5. App crashes 

**Code --** 

**Create room using **https://prod-in2.100ms.live/api/v2/rooms** API**
```
const createRoom = async (req, res) => {
  try {
    const {token,name,template} = JSON.parse(JSON.stringify(req.body));

    // create room 
    const response = await axios.post(
      "https://prod-in2.100ms.live/api/v2/rooms",
      {name,template,'region':'in',description:'demo room'},
      {
        headers: {
          "Content-type": "application/json",
          "Authorization": `Bearer ${token}`,
        },
      }
    );

    res.status(201).json({ room: response.data,token,message:"Room created successfully" });
  } catch (error) {
    res.status(500).json({ message: "Internal server error" });
  }
};
```

**response -** 
```
{
     id: '62da3844c16640065695a0d5',
    name: 'test1we',
    description: 'demo room',
    active: true,
    recording_source_template: true,
    template: 'twitterspaces_videoconf_a69e75f3-6970-451f-bc3f-c5d95sd950ba',
    template_id: '62c3ff6asf1c51f37af2224d5',
    region: 'in',
    user: '62c3df4dc42dc78aa5b8333e',
    customer: '62c3df4dc42dc78aa5b8333f',
    created_at: '2022-07-22T05:40:20.116837924Z',
    updated_at: '0001-01-01T00:00:00Z'
}
```

**Generate App token to Join the room.**
```
const getAppToken = async (req, res) => {
  const { room_id, user_id, role } = JSON.parse(JSON.stringify(req.body));

  const payload = {
    access_key: app_access_key,
    room_id: room_id,
    user_id: user_id,
    role: role,
    type: "app",
    version: 2,
    iat: Math.floor(Date.now() / 1000),
    nbf: Math.floor(Date.now() / 1000),
  };

  jwt.sign(
    payload,
    app_secret,
    {
      algorithm: "HS256",
      expiresIn: "24h",
      jwtid: uuid4(),
    },
    function (err, token) {
      if (err) {
        res.status(500).json({ message: err.message });
      }
      res.status(201).json({ token,message:"token successfully generated" });
    }
  );
};
```

**Response -** 

`{ token:"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3Nfa2V5IjoiNjJjM2RmNGRjNDJkYzc4YWE1YjgzMzQyIiwicm9vbV9pZCI6IjYyZGE35455zE2NjQwMDY1Njk1YTBkNSIsInVzZXJfaWQiOiJwcW1pZmx2eiIsInJvbGUiOiJob3N0IiwianRpIjoiNjA3YTU1MDMtNDQ4ZS00MGI5LTkzODMtZTRmY2JhN2MzMWViIiwidHlwZSI6ImFwcCIsInZlcnNpb24iOjIsImV4cCI6MTY1ODU1NjI1OX0.6yn0_HJHHmeDUlbOhWuFZ8Y3ehZOJwhW-eQrU8O7zIk",message:"token successfully generated" }`

**Join the room using token.**
```
final TokenResponse tokenResponse =
            await roomRepository.getAppToken(user: userId, roomId: roomId,role:'host');

        HMSConfig hmsConfig = HMSConfig(
          authToken: tokenResponse.token,
          userName: "Flutter user",
        );
        await SdkInitializer.hmssdk.join(config: hmsConfig);
       emit(JoinRoomState(event.room));
```
        
**App crashes with this log -** 

```
D/AuthTokenUtils(26382): getJWTPayload: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNjJjM2RmNGRjNDJkYzc4YWE1YjgzMzQyIiwicm9sZSI6Imhvc3QiLCJ0eXBlIjoiYXBwIiwidmVyc2lvbiI6MiwiaWF0IjoxNjU4NDY4MTA4LCJuYmYiOjE2NTg0NjgxMDgsImV4cCI6MTY1ODU1NDUwOCwianRpIjoiMmI5NTMyM2MtZTM0NS00ZTc5LThhMDUtNzI0MWM0Zjg2NjQ0In0.A7P_lqQLGTYT95e4Op2vidpyf0zBuPL_TnQgcUPkC1U
E/AndroidRuntime(26382): FATAL EXCEPTION: pool-11-thread-1
E/AndroidRuntime(26382): Process: com.company.app, PID: 26234
E/AndroidRuntime(26382): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter customerUserId
E/AndroidRuntime(26382): 	at live.hms.video.sdk.models.HMSLocalPeer.<init>(Unknown Source:2)
E/AndroidRuntime(26382): 	at live.hms.video.sdk.SDKStore.initWithConfig(SDKStore.kt:119)
E/AndroidRuntime(26382): 	at live.hms.video.sdk.SDKDelegate$join$2.invokeSuspend(SDKDelegate.kt:738)
E/AndroidRuntime(26382): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(26382): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(26382): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(26382): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26382): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(26382): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/AndroidRuntime(26382): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26382): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(26382): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/ViewRootImpl@f3c84ac[MainActivity](26382): MSG_WINDOW_FOCUS_CHANGED 0 1
I/Process (26382): Sending signal. PID: 26382 SIG: 9
Lost connection to device.
```

**Comment by ygit** [comment]
@asmitzz The Auth Token generated is incorrect. It does not contains `room_id` field.
I see this is the token used: 
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNjJjM2RmNGRjNDJkYzc4YWE1YjgzMzQyIiwicm9sZSI6Imhvc3QiLCJ0eXBlIjoiYXBwIiwidmVyc2lvbiI6MiwiaWF0IjoxNjU4NDY4MTA4LCJuYmYiOjE2NTg0NjgxMDgsImV4cCI6MTY1ODU1NDUwOCwianRpIjoiMmI5NTMyM2MtZTM0NS00ZTc5LThhMDUtNzI0MWM0Zjg2NjQ0In0.A7P_lqQLGTYT95e4Op2vidpyf0zBuPL_TnQgcUPkC1U
```

The decoded version of this token is:
```
{
  "access_key": "62c3df4dc42dc78aa5b83342",
  "role": "host",
  "type": "app",
  "version": 2,
  "iat": 1658468108,
  "nbf": 1658468108,
  "exp": 1658554508,
  "jti": "2b95323c-e345-4e79-8a05-7241c4f86644"
}
```
As you see, the `room_id` field is missing in the token, causing the crash.
You can deconstruct the JWT Auth Tokens here: https://jwt.io/

Also, don't use the Flutter version 3.0.5, use a version of the 2.x.x series, 2.10.5 or lower.
This is due to an ongoing issue in Flutter 3.x.x which causes Native Platform Views to be drawn at incorrect position. 
Refer: [107313](https://github.com/flutter/flutter/issues/107313) & [103630](https://github.com/flutter/flutter/issues/103630). 

We are actively tracking these issues & once they are released on Flutter [`stable`](https://github.com/flutter/flutter/tree/stable) branch, we'll release a compatible `hmssdk_flutter` version.

**Comment by asmitzz** [comment]
> @asmitzz The Auth Token generated is incorrect. It does not contains `room_id` field. I see this is the token used:
> 
> ```
> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNjJjM2RmNGRjNDJkYzc4YWE1YjgzMzQyIiwicm9sZSI6Imhvc3QiLCJ0eXBlIjoiYXBwIiwidmVyc2lvbiI6MiwiaWF0IjoxNjU4NDY4MTA4LCJuYmYiOjE2NTg0NjgxMDgsImV4cCI6MTY1ODU1NDUwOCwianRpIjoiMmI5NTMyM2MtZTM0NS00ZTc5LThhMDUtNzI0MWM0Zjg2NjQ0In0.A7P_lqQLGTYT95e4Op2vidpyf0zBuPL_TnQgcUPkC1U
> ```
> 
> The decoded version of this token is:
> 
> ```
> {
>   "access_key": "62c3df4dc42dc78aa5b83342",
>   "role": "host",
>   "type": "app",
>   "version": 2,
>   "iat": 1658468108,
>   "nbf": 1658468108,
>   "exp": 1658554508,
>   "jti": "2b95323c-e345-4e79-8a05-7241c4f86644"
> }
> ```
> 
> As you see, the `room_id` field is missing in the token, causing the crash. You can deconstruct the JWT Auth Tokens here: https://jwt.io/
> 
> Also, don't use the Flutter version 3.0.5, use a version of the 2.x.x series, 2.10.5 or lower. This is due to an ongoing issue in Flutter 3.x.x which causes Native Platform Views to be drawn at incorrect position. Refer: [107313](https://github.com/flutter/flutter/issues/107313) & [103630](https://github.com/flutter/flutter/issues/103630).
> 
> We are actively tracking these issues & once they are released on Flutter [`stable`](https://github.com/flutter/flutter/tree/stable) branch, we'll release a compatible `hmssdk_flutter` version.

That token is invalid. I have given that token just for the reference purpose.

**Comment by asmitzz** [comment]
@ygit This is the valid token.

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNjJjM2RmNGRjNDJkYzc4YWE1YjgzMzQyIiwidHlwZSI6Im1hbmFnZW1lbnQiLCJ2ZXJzaW9uIjoyLCJpYXQiOjE2NTg0NzUxMzYsIm5iZiI6MTY1ODQ3NTEzNiwiZXhwIjoxNjU4NTYxNTM2LCJqdGkiOiI2NjUwOGYwZC0yNWQ0LTQyN2UtOWQ2Yi1iMTE2ODUwYzMzNDAifQ.lGd_7aU3p2D8MOZKoo7B39X9eQOxwKAZx0pZqcA3D1k

**Comment by ygit** [comment]
@asmitzz This token is invalid that's why the crash is happening. It does not contain `room_id`, `role` & `user_id` fields.
Here's the decoded version of this Auth Token on [jwt.io](https://jwt.io/)


<img width="1180" alt="Screenshot 2022-07-22 at 9 34 34 PM" src="https://user-images.githubusercontent.com/8512357/180479145-b40eb8ae-2194-4e25-a190-f6bf12fb728a.png">
