### ISSUE TITLE
Please return exact data types on functions/methods.

### ISSUE THREAD

**Issue by yahu1031** [100mslive/100ms-flutter#790]
I see this `join()` function is async and doesn't have Future. Even after having strict lint rules in app I suspect join to be a future and checked the source code. Then I found it is. Please use `Future<Type>` if needed.

https://github.com/100mslive/100ms-flutter/blob/f2e2ce4af68f7b164630fbcf0f019423b65f999f/lib/src/hmssdk.dart#L47

Regards.

**Comment by yahu1031** [comment]
https://github.com/100mslive/100ms-flutter/blob/main/lib/src/hmssdk.dart#L279

**Comment by ygit** [comment]
@yahu1031 We have resolved these in [this PR](https://github.com/100mslive/100ms-flutter/pull/791). This will be released soon in the next version of the SDK.
