### ISSUE TITLE
The getter 'name' isn't defined for the class 'HMSAudioDevice'

### ISSUE THREAD

**Issue by madhukarNumen** [100mslive/100ms-flutter#856]
Unable to integrate 100ms sdk hmssdk_flutter: 0.7.6 to flutter app. Getting below error:

../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/hmssdk.dart:769:57: Error: The getter 'name' isn't defined for the class 'HMSAudioDevice'.
 - 'HMSAudioDevice' is from 'package:hmssdk_flutter/src/enum/hms_audio_device.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/enum/hms_audio_device.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
          arguments: {"audio_device_name": audioDevice!.name});
                                                        ^^^^
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/hmssdk.dart:781:58: Error: The getter 'name' isn't defined for the class 'HMSAudioMixingMode'.
 - 'HMSAudioMixingMode' is from 'package:hmssdk_flutter/src/enum/hms_audio_mixing_mode.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/enum/hms_audio_mixing_mode.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
        arguments: {"audio_mixing_mode": audioMixingMode.name});
                                                         ^^^^
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/hmssdk.dart:814:60: Error: The getter 'name' isn't defined for the class 'HMSAudioMixingMode'.
 - 'HMSAudioMixingMode' is from 'package:hmssdk_flutter/src/enum/hms_audio_mixing_mode.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/hmssdk_flutter-0.7.6/lib/src/enum/hms_audio_mixing_mode.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
          arguments: {"audio_mixing_mode": audioMixingMode.name});
                                                           ^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/user/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/user/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.5 21G72 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)

• No issues found!

I really want to use 100ms for video call in our app. Please help me on this issue.

**Comment by Decoder07** [comment]
Hi @madhukarNumen can you update your flutter version and try.

**Comment by madhukarNumen** [comment]
HI @Decoder07 thanks for the quick response. As per documentation, any flutter version greater than 2.0.0  is fine for 100ms integration.

Minimum Configuration 
Support for Android API level 21 or higher
Support for Java 8
Support for iOS 10 or higher
Support for Flutter 2.x.x or higher (except 3.0.0 to 3.0.5)
Xcode 12 or higher

And I am using 2.5.3. Which should be fine.
If required, which flutter version should I update to, since using flutter version greater than 3.0.0 is not recommended.

**Comment by Decoder07** [comment]
name property was added in flutter 2.10.x release: https://github.com/flutter/flutter/pull/94496

**Comment by ygit** [comment]
@madhukarNumen You can upgrade to any latest stable Flutter version 3.3.0 or above: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

**Comment by ygit** [comment]
@madhukarNumen Were you able to resolve this issue?

**Comment by madhukarNumen** [comment]
Thank you @ygit. Yes updating flutter to 3.3.3 solved the issue. Can I have a complete updated documentation to integrate 100ms for flutter?

**Comment by Decoder07** [comment]
You can find the doc here: https://www.100ms.live/docs/flutter/v2/guides/quickstart

**Comment by madhukarNumen** [comment]
@Decoder07  Thank you
