### ISSUE TITLE
app is crashed on calling method hmssdk.startScreenShare()

### ISSUE THREAD

**Issue by amitmallah0509** [100mslive/100ms-flutter#873]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=192, result=-1, data=Intent { (has extras) }} to activity {com.queira.clinicjet_device/com.queira.clinicjet_device.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property hmssdk has not been initialized

i have added all permissions
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-feature android:name="android.hardware.camera"/>
    <uses-feature android:name="android.hardware.camera.autofocus"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

my main activity code

     import io.flutter.embedding.android.FlutterActivity
     import live.hms.hmssdk_flutter.HmssdkFlutterPlugin
     import android.app.Activity
     import android.content.Intent
     import live.hms.hmssdk_flutter.Constants

     class MainActivity: FlutterActivity() {
         override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
             super.onActivityResult(requestCode, resultCode, data)
             if (requestCode == Constants.SCREEN_SHARE_INTENT_REQUEST_CODE && resultCode == Activity.RESULT_OK){
                 if (data != null) {
                     HmssdkFlutterPlugin.hmssdkFlutterPlugin?.requestScreenShare(data)
                 }
             }
         }
     }

my dart file code

     class Page extends StatefulWidget {
       const Page({Key? key}) : super(key: key);

       @override
       State<Page> createState() => _PageState();
     }

     class _PageState extends State<Page> {

     @override
       void initState() {
         super.initState();
         hmssdk.build();
       }

     @override
       Widget build(BuildContext context) {

     return Container(
                            height: 50,
                            decoration: BoxDecoration(
                              color: Colors.blue.shade400,
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: TextButton(
                              child: Text(
                                isScreenShareActive == true
                                    ? "Stop Screen Share"
                                    : "Start Screen Share",
                                style: const TextStyle(color: Colors.white),
                              ),
                              style: TextButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 20)),
                              onPressed: () async {
                                if (isScreenShareActive == true) {
                                  hmssdk.stopScreenShare(
                                      hmsActionResultListener:
                                          hmsActionResultListen);
                                  isScreenShareActive = false;
                                } else {
                                  hmsActionResultListen =
                                      HMSActionResultListen();
                                  hmssdk.startScreenShare(
                                      hmsActionResultListener:
                                          hmsActionResultListen);
                                  isScreenShareActive = true;
                                }
                                setState(() {});
                              },
                            ))
     )

**Comment by Decoder07** [comment]
Hi @amitmallah0509 which sdk version are you using ?

**Comment by amitmallah0509** [comment]
i have tried both sdk version hmssdk_flutter: ^0.6.0 and hmssdk_flutter: ^0.7.6

**Comment by amitmallah0509** [comment]
> Hi @amitmallah0509 which sdk version are you using ?
@Decoder07  i have tried both sdk version hmssdk_flutter: ^0.6.0 and hmssdk_flutter: ^0.7.6

**Comment by Decoder07** [comment]
Ok and which state management library are you using ?

**Comment by amitmallah0509** [comment]
> Ok and which state management library are you using ?
i am using getx state management library.

but problem in hmssdk when i called startScreenShare() method then it triggered HmssdkFlutterPlugin.hmssdkFlutterPlugin?.requestScreenShare(data) code. which is in mainactivity.kt file. the issue is in requestScreenShare method and it showing "hmssdk is not Initialized" in console log.

**Comment by Decoder07** [comment]
Can you verify your implementation from here : https://github.com/100mslive/100ms-flutter/tree/main/sample%20apps/getx

Are you getting the permission popup while calling `startScreenShare` ?

**Comment by amitmallah0509** [comment]
> Can you verify your implementation from here : https://github.com/100mslive/100ms-flutter/tree/main/sample%20apps/getx
> 
> Are you getting the permission popup while calling `startScreenShare` ?

Yes

**Comment by Decoder07** [comment]
Hi @amitmallah0509  can you try the sdk from this branch : [screen-share-fix](https://github.com/100mslive/100ms-flutter/tree/fix/screenshare-crash)

**Comment by ygit** [comment]
hey @amitmallah0509 Were you able to resolve this issue?

**Comment by ygit** [comment]
hey @amitmallah0509 
Assuming that this issue is resolved now, closing this ticket.

**Comment by amitmallah0509** [comment]
> hey @amitmallah0509 Were you able to resolve this issue?

Thanks it fixed
