### ISSUE TITLE
[!] The 'Pods-Runner' target has frameworks with conflicting names: webrtc.xcframework. getting this while running pod install

### ISSUE THREAD

**Issue by mayukhU25** [100mslive/100ms-flutter#877]
Running on iOS 16.0.2.
xCode Version 14

**Comment by ygit** [comment]
hey @mayukhU25 

Are you using any other library which depends on `WebRTC`? 
It's possible that `Pods/` contains older library data as well.

What's your Flutter version? This can be checked using `flutter doctor`.

Check that in your `ios/Podfile` file, the correct minimum iOS deployment target is set. It should be iOS 12 or above.
`platform :ios, '12.0'`

Ensure you are following all the steps for integration mentioned here: https://www.100ms.live/docs/flutter/v2/features/integration

**Comment by ygit** [comment]
hey @mayukhU25 
Were you able to resolve this issue?

**Comment by ygit** [comment]
hey @mayukhU25 
Assuming that this issue is resolved now, closing this ticket.
