### ISSUE TITLE
Only display peers with audio or video track

### ISSUE THREAD

**Issue by Decoder07** [100mslive/100ms-flutter#906]
Remove the peers without audio and video track from UI but show them in participant list.

**Comment by ygit** [comment]
- `PeerTrackNodes` should only be created for tiles to be shown on screen.
- So roles which publish neither audio nor video, `PeerTrackNodes` should not be created.
- Since audio only roles are expected to be visible as a tile, `PeerTrackNodes` should be created for roles which publish only audio.
