### ISSUE TITLE
live streaming his viewer's video track not coming in onTrackUpdate

### ISSUE THREAD

**Issue by vorachirag318** [100mslive/100ms-flutter#922]

**Comment by Decoder07** [comment]
Hi @vorachirag318 there are no publish permissions for hls role and if you are looking for HLS stream url, you will get that in `HMSRoom` object in `onRoomUpdate` callback.

**Comment by vorachirag318** [comment]
In live streaming, how can I show the broadcaster's track to the his-viewer?

**Comment by vorachirag318** [comment]
In live streaming, how can I show the broadcaster's track to the his-viewer?

**Comment by Decoder07** [comment]
@vorachirag318  please check the implementation here : https://www.100ms.live/docs/flutter/v2/features/hls#display-hls-stream

**Comment by ygit** [comment]
hey @vorachirag318 
Were you able to implement this?

**Comment by vorachirag318** [comment]
yes, working now

**Comment by vorachirag318** [comment]
how to HLS streaming start recording and how to save recording video on the broadcaster side?

**Comment by Decoder07** [comment]
There is a property which you can use to start recording with HLS : https://www.100ms.live/docs/flutter/v2/features/hls
Please check the implementation above.

**Comment by vorachirag318** [comment]
![Screenshot 2022-11-15 at 12 29 00 PM](https://user-images.githubusercontent.com/97113308/201851213-f54baafb-66ab-42c5-8a41-7f98e1374843.png)

What will this callback come from?

**Comment by Decoder07** [comment]
Once HLS starts you will get `onRoomUpdate` callback and in that callback you will get the `streamUrl` in `HMSRoom` object.You can check the implementation from above doc link.

**Comment by vorachirag318** [comment]
Where to get record video url to store recording video in aws bucket.

**Comment by ygit** [comment]
hey @vorachirag318 
Do refer to this doc for fetching the Recording from AWS: https://www.100ms.live/docs/server-side/v2/introduction/recordings

**Comment by vorachirag318** [comment]
i read your given documentation and i didn't found mp4 video in "bucketlocation/prefix/beam/roomid/datetime"
![WhatsApp Image 2022-11-19 at 2 09 25 PM](https://user-images.githubusercontent.com/97113308/202842636-3a60ecbc-a3a8-4012-9d25-2c1e9efdfb2b.jpeg)

**Comment by ygit** [comment]
hey @vorachirag318 
Let's connect over a call to debug the Recording issue
https://calendly.com/yogesh-singh-100ms/30min

**Comment by ygit** [comment]
hey @vorachirag318 
As discussed over the call yesterday, hope all your queries are resolved now.
