### ISSUE TITLE
Apk Build in Mac doesnt Work 

### ISSUE THREAD

**Issue by WilliamBz12** [100mslive/100ms-flutter#946]
I'm trying to build a version for the android app but I keep getting an error. But when trying to do it on Windows the apk build  correctly.

The error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hmssdk_flutter:compileReleaseKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':hmssdk_flutter:compileReleaseKotlin'
   > Could not resolve all files for configuration ':hmssdk_flutter:releaseCompileClasspath'.
      > Failed to transform webrtc-m104-hms-1.3.jar (com.github.100mslive:webrtc:m104-hms-1.3) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find webrtc-m104-hms-1.3.jar (com.github.100mslive:webrtc:m104-hms-1.3).
           Searched in the following locations:
               https://www.jitpack.io/com/github/100mslive/webrtc/m104-hms-1.3/webrtc-m104-hms-1.3.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.`

**Comment by Decoder07** [comment]
Hi @WilliamBz12 which sdk version is this ?

**Comment by LuisMiguelMP** [comment]
Hi @Decoder07 and @WilliamBz12, same issue here. Android SDK version 33, hmssdk_flutter 0.7.8.

**Comment by Decoder07** [comment]
Can you try removing the package from `.pub-cache` and run `flutter pub get` again.

**Comment by LuisMiguelMP** [comment]
> Can you try removing the package from `.pub-cache` and run `flutter pub get` again.

Thanks @Decoder07. Still having the problem. I realized that sometimes the build works, sometimes it doesn't. 🫣

**Comment by Decoder07** [comment]
Hi @LuisMiguelMP let's get on a call and discuss.Can you book a slot here: 
https://calendly.com/pushpam-saxena/30min

**Comment by Decoder07** [comment]
Hi @LuisMiguelMP @WilliamBz12  we have found the issue, we will be releasing a new SDK that should fix this issue.

**Comment by LuisMiguelMP** [comment]
@Decoder07 Thank you very much for your availability and agility!
I canceled our call. 
Good rest of the week!
