### ISSUE TITLE
In IOS hmsTrackSetting back camera not working. what is the problem?

### ISSUE THREAD

**Issue by vorachirag318** [100mslive/100ms-flutter#977]

**Comment by ygit** [comment]
hey @vorachirag318 Do you want to set the back camera while joining the room?

We'll be releasing support for this soon.

Meanwhile, you can call `switchCamera()` in `onJoin` event to show the back camera.

**Comment by ygit** [comment]
hey @vorachirag318 We have released new version [1.1.0](https://pub.dev/packages/hmssdk_flutter) which fixes this issue. Try it out & let us know.

**Comment by ygit** [comment]
hey @vorachirag318 
Were you able to try out the new package version [1.1.0](https://pub.dev/packages/hmssdk_flutter) ?

**Comment by ygit** [comment]
hey @vorachirag318 
Hope you were able to resolve this issue. Ping us on Discord for any other assistance: https://100ms.live/discord
