### ISSUE TITLE
 MissingPluginException(No implementation found for method build on channel hmssdk_flutter)

### ISSUE THREAD

**Issue by devmike01** [100mslive/100ms-flutter#988]
I'm trying to use this `100ms-flutter` `v1.0.0` in my project but getting the following error.

```
MissingPluginException(No implementation found for method build on channel hmssdk_flutter)
E/flutter (10515): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #1      PlatformService.invokeMethod (package:hmssdk_flutter/src/service/platform_service.dart:103:18)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #2      HmsSdkManager.createHMSSdk (package:hmssdk_flutter/src/manager/hms_sdk_manager.dart:23:12)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #3      HMSSDK.build (package:hmssdk_flutter/src/hmssdk.dart:33:5)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): 
I/flutter (10515): objectException ====> MissingPluginException(No implementation found for method join on channel hmssdk_flutter)

```

My codes
```
final hmsSDK = HMSSDK();
hmsSDK.build()
hmsSDK.addUpdateListener(listener: this);
```

I have looked at my codes and couldn't find anything wrong. Kindly assist.

**Comment by devmike01** [comment]
Hello, thank you for your response. I have tried these commands multiple times but to no avail. I keep on getting the same exception.

**Comment by ygit** [comment]
hey @devmike01 
We are not able to reproduce this issue.
Let's get on a call to debug this further: https://calendly.com/yogesh-singh-100ms/30min

**Comment by devmike01** [comment]
Hello, I have scheduled a meeting. Thanks

**Comment by ygit** [comment]
hey @devmike01 
As we discussed on the call, were you able to update the Auth Token used in creating HMSConfig?
Were you able to resolve the this issue?

**Comment by devmike01** [comment]
Hey, I have been busy. I will try it out this week and revert.

**Comment by ygit** [comment]
hey @devmike01 
Were you able to resolve this issue?

**Comment by devmike01** [comment]
Hey, apologies for the late response. I followed your advice and I'm still getting the same error. This is the decoded JWT string.

```
{
  "access_key": "63822f5d195ad14bdcd6edb5",
  "type": "app",
  "role": "user",
  "room_id": "63a3a58343d26018a492fc6b",
  "user_id": "lc2hu4kugmnmm8ff3z",
  "version": 2,
  "iat": 1671919725,
  "nbf": 1671919725,
  "exp": 1672006125,
  "jti": "2bcc7407-ecaa-40ec-93f7-47afea485237"
}
```

**Comment by ygit** [comment]
hey @devmike01 
Were you able to resolve this issue?

Do refer to these Docs -

Token Generation Guide: https://www.100ms.live/docs/flutter/v2/guides/token

Join Room: https://www.100ms.live/docs/flutter/v2/features/join

**Comment by devmike01** [comment]
No, I switched to another package.
